spring:
  datasource:
    url: jdbc:h2:file:~/bookstore_prod;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIST=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  h2:
    console:
      enabled: false

logging:
  level:
    br:
      com:
        carlosrobson: INFO